# Generated by Django 5.2.1 on 2025-05-28 19:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
                'indexes': [models.Index(fields=['name'], name='organizatio_name_5cd1d4_idx'), models.Index(fields=['created_at'], name='organizatio_created_8a4b5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrgUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organizations.organization')),
            ],
            options={
                'db_table': 'org_users',
                'indexes': [models.Index(fields=['email'], name='org_users_email_f874f4_idx'), models.Index(fields=['org', 'role'], name='org_users_org_id_b42956_idx'), models.Index(fields=['created_at'], name='org_users_created_310e15_idx')],
                'constraints': [models.UniqueConstraint(fields=('email',), name='unique_email_org_user')],
            },
        ),
    ]
